"""Read/write the exclusion list for a driver's dynamic-shape (resolution-resizability)
check: models whose guard-solving time depends on the machine rather than the
architecture, so they are reported as `excluded` instead of measured.
"""
import os

import yaml


def parse_exclusions(path):
    """{model: reason} from the exclusion file, or {} if there is none."""
    if not path or not os.path.exists(path):
        return {}
    with open(path) as f:
        document = yaml.load(f, Loader=getattr(yaml, 'CSafeLoader', yaml.SafeLoader)) or {}
    return {name: str(entry) for name, entry in (document.get('models') or {}).items()}


def render_exclusions(excluded, dynamic_timeout):
    """The models whose dynamic-shape check ran out of budget, as a file to commit.

    `excluded` is a sorted iterable of model names. Whether one of these converges is a
    fact about how fast the machine is, not about the architecture, so instead of letting
    the verdict vary by machine, the slow ones are listed here once, deliberately, and
    reported as `excluded` from then on.
    """
    lines = [
        '# Models excluded from the dynamic-shape (`dynamic (export)`) check.',
        '#',
        '# Generated by `make report.exclusions`, do not edit by hand -- and regenerate it',
        f'# rather than adding entries, so every listed model was measured the same way.',
        f'# These exceeded the {dynamic_timeout}s guard-solving budget, which makes their',
        '# result depend on machine speed; `make report` reports them as `excluded`.',
        '',
        'models:',
    ]
    for name in excluded:
        lines.append(f'  {name}: guard solving exceeded the {dynamic_timeout}s budget')
    lines.append('')
    return '\n'.join(lines)
