#!/usr/bin/env python3
"""Report (operator, configuration) coverage and family breadth as a function of model count.

`select_models.py` picks a fixed-size subset; this instead re-runs the same `select()` at
every target in steps of 10, from 10 up to the point the algorithm saturates on its own (no
eligible candidate gains anything further), so the actual shape of the coverage-vs-count curve
is something to look at and decide `--target` from, rather than something to guess.
"""
import argparse
import os
import sys

import yaml

from select_models import load_candidates, load_popularity, select


def curve(candidates, popularity, max_nodes, max_weight_mb, step):
    all_ops = set().union(*(c['ops'] for c in candidates.values()))
    all_families = {c['family'] for c in candidates.values()}

    # Uncapped run to find where the algorithm stops adding anything on its own -- the natural
    # ceiling, past which a bigger --target would just repeat this same selection.
    saturated = select(candidates, 10**9, max_nodes, max_weight_mb, [], set(), popularity)
    max_models = len(saturated)

    targets = list(range(step, max_models, step)) + [max_models]
    points = []
    for target in targets:
        selected = select(candidates, target, max_nodes, max_weight_mb, [], set(), popularity)
        covered_ops = set().union(*(candidates[n]['ops'] for n, _ in selected)) if selected else set()
        covered_families = {candidates[n]['family'] for n, _ in selected}
        points.append({
            'target': target,
            'models': len(selected),
            'op_configs_covered': len(covered_ops),
            'op_configs_total': len(all_ops),
            'op_configs_pct': round(100 * len(covered_ops) / len(all_ops), 1),
            'families_covered': len(covered_families),
            'families_total': len(all_families),
            'families_pct': round(100 * len(covered_families) / len(all_families), 1),
            'total_nodes': sum(candidates[n]['nodes'] for n, _ in selected),
        })
    return points, max_models, len(all_ops), len(all_families)


def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--models-md', default=os.path.join(repo_root, 'models.md'))
    parser.add_argument('--ops', default=os.path.join(repo_root, 'ops.yaml'))
    parser.add_argument('--popularity', default=os.path.join(repo_root, 'model-popularity.yaml'))
    parser.add_argument('--output', default=os.path.join(repo_root, 'coverage-curve.yaml'))
    parser.add_argument('--step', type=int, default=10)
    parser.add_argument('--max-nodes', type=int, default=2500)
    parser.add_argument('--max-weight', type=float, default=150.0)
    args = parser.parse_args()

    candidates = load_candidates(args.models_md, args.ops)
    popularity = load_popularity(args.popularity)

    points, max_models, total_ops, total_families = curve(
        candidates, popularity, args.max_nodes, args.max_weight, args.step)

    document = {
        'max_nodes': args.max_nodes,
        'max_weight_mb': args.max_weight,
        'op_configs_total': total_ops,
        'families_total': total_families,
        'natural_saturation_models': max_models,
        'points': points,
    }
    header = (
        '# Coverage vs. model count, in steps of {step} -- what scripts/select_models.py would\n'
        '# produce at each --target, from 10 up to natural_saturation_models (the point past\n'
        '# which a bigger --target selects nothing new; the last point in `points` is always\n'
        '# this value even if it is not a multiple of {step}).\n'
        '#\n'
        '# Generated by scripts/coverage_curve.py -- regenerate with `make models.curve`.\n'
        '# Meant to be read by eye to pick --target for `make models.select`: the target where\n'
        '# op_configs_pct/families_pct stop climbing much per extra 10 models is the point past\n'
        '# which more models buy little beyond bigger archives.\n'
        '\n'
    ).format(step=args.step)
    with open(args.output, 'w') as f:
        f.write(header)
        f.write(yaml.safe_dump(document, sort_keys=False, default_flow_style=False, width=100))

    print(f'Wrote {args.output}: {len(points)} points, saturates at {max_models} models', file=sys.stderr)


if __name__ == '__main__':
    main()
