#!/usr/bin/env python3
"""Fetch per-repo download counts from the HuggingFace Hub, as a popularity signal for
`scripts/select_models.py`.

`ops.yaml`/`models.md` say what a model costs to export; neither says whether anyone actually
uses it. The `timm` org on the Hub carries a download count per pretrained tag, which is the
cheapest real usage signal available for the whole zoo at once. This fetches it in a single
paginated call and commits the result -- the same reason `make report` commits an export pass
rather than `select_models.py` exporting anything itself -- so `models.select` stays a
seconds-long, offline, reviewable-in-a-diff step.
"""
import argparse
import os
import sys

import yaml
from huggingface_hub import HfApi


def fetch(author):
    """{repo name relative to `author`: downloads} for every repo under `author`.

    The `timm/` org prefix is stripped rather than kept as part of the key: this repo only
    ever fetches one author, so every key would carry the same redundant prefix, and
    select_models.py only cares about the part after it anyway.
    """
    api = HfApi()
    prefix = f'{author}/'
    return {info.id.removeprefix(prefix): int(info.downloads or 0)
            for info in api.list_models(author=author, limit=None)}


def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--author', default='timm', help='Hub org/user to enumerate models for')
    parser.add_argument('--output', default=os.path.join(repo_root, 'model-popularity.yaml'))
    args = parser.parse_args()

    downloads = fetch(args.author)
    if not downloads:
        sys.exit('no models returned from the Hub -- check network access')

    document = {
        'source': f'huggingface.co API, list_models(author="{args.author}").downloads',
        'author': args.author,
        'repos': len(downloads),
        # Descending by downloads (ties by repo name) so the file itself reads as a popularity
        # ranking -- useful to skim by hand, not just for select_models.py to consume.
        'downloads': dict(sorted(downloads.items(), key=lambda kv: (-kv[1], kv[0]))),
    }
    header = (
        f'# Per-repo download counts (last 30 days) from the HuggingFace Hub, keyed by repo name\n'
        f'# relative to the `{args.author}/` org (e.g. `efficientnet_b0.ra_in1k`, not\n'
        f'# `{args.author}/efficientnet_b0.ra_in1k`), sorted most-downloaded first.\n'
        '#\n'
        '# Generated by scripts/fetch_popularity.py -- regenerate with `make models.popularity`.\n'
        '# select_models.py sums this across every repo whose name (the part before the first\n'
        '# `.<tag>`) matches a timm model name, since one variant can ship several pretrained\n'
        '# tags, each a separate repo with its own count.\n'
        '\n'
    )
    with open(args.output, 'w') as f:
        f.write(header)
        f.write(yaml.safe_dump(document, sort_keys=False, default_flow_style=False, width=100))

    print(f'Wrote {args.output}: {len(downloads)} repos', file=sys.stderr)


if __name__ == '__main__':
    main()
